# fly.toml app configuration file generated for python-project on 2023-06-11T16:58:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "python-project"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
