name: Build and deploy
on:
  push:
    branches:
      - master

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - run: curl -L https://fly.io/install.sh | sh
      - run: flyctl -t $FLY_TOKEN deploy
        env:
          FLY_TOKEN: ${{ secrets.FLY_TOKEN }}
